### ISSUE TITLE
Calling Julia code from MATLAB

### ISSUE THREAD

**Issue by mchitre** [org-arl/jajub#1]
Issue transferred here from email

---

thanks for your jajub package!

It could be very interesting for Matlab too, because Java is Matlab's second internal language.
The usual Mex C-interface is broken since 3 years.

I compiled the java files and put them in a jar. 
In Matlab:
```
>> javaaddpath('jajub.jar');
>> import org.arl.jajub.*
>> methods JuliaBridge
Methods for class JuliaBridge:
JuliaBridge      eval             getClass         notifyAll 
...
```

The environment variable is set
```
>> ls([getenv('JULIA_HOME'), '/bin/julia.exe'])
julia.exe  
```

Then I tried your example:
```
>> julia = JuliaBridge
julia = org.arl.jajub.JuliaBridge@6d303498

>> julia.open
Java exception occurred:
java.io.IOException: Bad Julia process
	at org.arl.jajub.JuliaBridge.open(JuliaBridge.java:106)
	at org.arl.jajub.JuliaBridge.open(JuliaBridge.java:118)
```

What could have gone wrong?

**Comment by mchitre** [comment]
Calling Julia from MATLAB using JaJuB should be possible, although I have not tried it personally.

The exception suggests a timeout in starting the Julia process. Have you tried running `julia` manually from command line to make sure Julia runs fine on your machine? If, for some reason, startup is slow (the default timeout is 10 seconds), you can call `open()` with a timeout argument (in ms) to try if a longer timeout helps.

**Comment by bardo84** [comment]
Manual calling yields an immediate response:
```
>> system('julia -E "2+2"');
4
```

**Comment by mchitre** [comment]
Try:
```
import org.arl.jajub.*
j = new JuliaBridge()
j.open(30000)   // longer timeout (30 s)
j.getJuliaVersion()
j.close()
```

**Comment by bardo84** [comment]
Then throwing the same error after 30s.

**Comment by mchitre** [comment]
What OS are you running on?

**Comment by bardo84** [comment]
Win10, and just tested, same on Linux:

Java exception occurred:
java.io.IOException: Bad Julia process
	at org.arl.jajub.JuliaBridge.open(JuliaBridge.java:106)
 
>> system('julia -E "2+2"')
4

**Comment by mchitre** [comment]
Can you try this Groovy code on a `groovysh` on the same machine?
```
import org.arl.jajub.*
j = new JuliaBridge()
j.open(30000)   // longer timeout (30 s)
j.getJuliaVersion()
j.close()
```
(or if you prefer, put it in a Java class and run it)

Trying to figure out if this is some permission problem from the MATLAB JVM or something more general. I don't have access to MATLAB to test for the next few weeks, but might be able to test myself later in August.

**Comment by mchitre** [comment]
@bardo84 Any update?

**Comment by mchitre** [comment]
Closing for lack of activity.
